### ISSUE TITLE
Pip requirement for setup.py cannot require data tools

### ISSUE THREAD

**Issue by bastienboutonnet** [bastienboutonnet/sheetload#13]
`git+ssh://git@github.com/tripactions/Data_Tooling.git@v1.8.7#egg=data-tools` is not supported by `install_requires=` arg in `setuptools`

**Comment by optroodt** [comment]
The fact that you can install packages through `git+ssh://...` doesn't make it a good idea. The only (proper) way to resolve this would be to host `data_tools` in a PyPI repo... 

Remember that we now build and publish `data_tools` to our Azure PyPI repository. During the Azure DS platform presentation we showed you how to setup PyPI credentials to install the `tacli` (TA command line interface), if you would do that globally (not just for a single venv) you can just refer to `data_tools==1.9.3`.

Does this help?

**Comment by bastienboutonnet** [comment]
@optroodt that's a very very legit point! This code was written before the presentation I believe so I didn't know that was an option. 

I'd go down that road and implement this solution, but that would require that everyone be able to have `tacli` credentials globally (e.g. analysts who might need to still upload sheets). If we're ok with that then we can make that option a default. Otherwise we'll have to keep the ugly shit for now.

Let me know what you think :)

**Comment by bastienboutonnet** [comment]
Closing this as it's resolved but we might have issue dealing with forcing upgrading the package
