### ISSUE TITLE
Remove case sensitivity

### ISSUE THREAD

**Issue by karolinaosiak** [bastienboutonnet/sheetload#37]
**Is your feature request related to a problem? Please describe.**
Right now, it is a bit confusing to use variable names in schema.yml, as the names are case sensitive.

**Describe the solution you'd like**
It would be great to have the variable names lowercased.

**Comment by bastienboutonnet** [comment]
Thanks for the feedback @karolinaosiak . Let me see if I understand your request correctly:
Would you like to be able to populate the `sheets.yml` file with the columns format as it is in the origin file? (and then have the cleanups be applied on the yml behind the scenes?)

Or does this update  #40 solve the issue/is enough?

If the columns in the yml should be handled, we'll have to see what we can do as yml parsing with all sorts of ugly names like ` . 1--__ActiVitiType__ ` would require people to properly enclose the column names in `""` etc. But it's not impossible I think.

**Comment by karolinaosiak** [comment]
That's a tricky one and the decision I leave up to you, but I was a bit confused if in the .yml I should use the exact - frequently ugly (ie. ZenDesk Id) names or remove spacebars or replace them with underscores. I checked update #40, but I can't find this info (might be missing it already).

**Comment by bastienboutonnet** [comment]
Yeah I get it, there should be an explanation added, I mean I can see it, but I know where to look so I'll have to give the documention a bit more love I think.

Regarding the feature, I really need to think about it, I totally get it that it's a painpoint now. But the solution isn't as straightfoward to implement.

**Comment by bastienboutonnet** [comment]
@karolinaosiak I **think** case sensitivity isn't an issue actually. But yes you still have to write the name as you would expect it to end up on the target. However, I think that with the implementation of #58 this is now easier since you can refer to the original column by it's "ugly" name in the `identifier:` field and offer a recode on the `name:` field.
