### ISSUE TITLE
Adding an option to rename a column

### ISSUE THREAD

**Issue by karolinaosiak** [bastienboutonnet/sheetload#51]
**Is your feature request related to a problem? Please describe.**
Sometimes column names in gsheets are well - crap. It would be great to be able to rename them.

**Describe the solution you'd like**
Option to rename a column name from the source

**Describe alternatives you've considered**
Enabling column names longer than 255 signs but to be honest I think that's much already

**Comment by bastienboutonnet** [comment]
Closed by #58
